### ISSUE TITLE
短すぎる動画がエンディングとして流れたときに自動で次枠待機状態になる機能

### ISSUE THREAD

**Issue by komatti365** [nucosen/Broadcast#104]
運用中に短い動画をエンディングに指定したら30分ほどダウンしてしまったので
もしかしたら違うバグの可能性もありますが
ログ
```
Oct 28 21:53:03 nucosen nucosen[9917]: 2023-10-28 21:53:03,803 [INFO] 引用を開始します: sm42921973
Oct 28 21:56:43 nucosen nucosen[9917]: 2023-10-28 21:56:43,670 [INFO] 引用終了見込み時刻になりました
Oct 28 21:56:46 nucosen nucosen[9917]: 2023-10-28 21:56:46,334 [INFO] 引用を開始します: sm42350228
Oct 28 21:56:47 nucosen nucosen[9917]: 2023-10-28 21:56:47,251 [INFO] 引用アボート: 時間内に引用が終了しない見込みです
Oct 28 21:56:50 nucosen nucosen[9917]: 2023-10-28 21:56:50,077 [INFO] 400 Error Log ==========
Oct 28 21:56:50 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:56:50 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:56:50 nucosen nucosen[9917]: Response body ;
Oct 28 21:56:50 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:56:50 nucosen nucosen[9917]: 2023-10-28 21:56:50,078 [WARNING] W01 引用拒否発生, retrying in 5 seconds...
Oct 28 21:56:57 nucosen nucosen[9917]: 2023-10-28 21:56:57,307 [INFO] 400 Error Log ==========
Oct 28 21:56:57 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:56:57 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:56:57 nucosen nucosen[9917]: Response body ;
Oct 28 21:56:57 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:56:57 nucosen nucosen[9917]: 2023-10-28 21:56:57,309 [WARNING] W01 引用拒否発生, retrying in 10 seconds...
Oct 28 21:57:09 nucosen nucosen[9917]: 2023-10-28 21:57:09,556 [INFO] 400 Error Log ==========
Oct 28 21:57:09 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:57:09 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:57:09 nucosen nucosen[9917]: Response body ;
Oct 28 21:57:09 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:57:09 nucosen nucosen[9917]: 2023-10-28 21:57:09,557 [WARNING] W01 引用拒否発生, retrying in 20 seconds...
Oct 28 21:57:32 nucosen nucosen[9917]: 2023-10-28 21:57:32,406 [INFO] 400 Error Log ==========
Oct 28 21:57:32 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:57:32 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:57:32 nucosen nucosen[9917]: Response body ;
Oct 28 21:57:32 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:57:32 nucosen nucosen[9917]: 2023-10-28 21:57:32,408 [WARNING] W01 引用拒否発生, retrying in 40 seconds...
Oct 28 21:58:15 nucosen nucosen[9917]: 2023-10-28 21:58:15,477 [INFO] 400 Error Log ==========
Oct 28 21:58:15 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:58:15 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:58:15 nucosen nucosen[9917]: Response body ;
Oct 28 21:58:15 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:58:15 nucosen nucosen[9917]: 2023-10-28 21:58:15,479 [WARNING] W01 引用拒否発生, retrying in 80 seconds...
Oct 28 21:59:37 nucosen nucosen[9917]: 2023-10-28 21:59:37,925 [INFO] 400 Error Log ==========
Oct 28 21:59:37 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 21:59:37 nucosen nucosen[9917]: Cookie : Good
Oct 28 21:59:37 nucosen nucosen[9917]: Response body ;
Oct 28 21:59:37 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 21:59:37 nucosen nucosen[9917]: 2023-10-28 21:59:37,926 [WARNING] W01 引用拒否発生, retrying in 160 seconds...
Oct 28 22:02:20 nucosen nucosen[9917]: 2023-10-28 22:02:20,699 [INFO] 400 Error Log ==========
Oct 28 22:02:20 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 22:02:20 nucosen nucosen[9917]: Cookie : Good
Oct 28 22:02:20 nucosen nucosen[9917]: Response body ;
Oct 28 22:02:20 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 22:02:20 nucosen nucosen[9917]: 2023-10-28 22:02:20,701 [WARNING] W01 引用拒否発生, retrying in 320 seconds...
Oct 28 22:07:43 nucosen nucosen[9917]: 2023-10-28 22:07:43,196 [INFO] 400 Error Log ==========
Oct 28 22:07:43 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 22:07:43 nucosen nucosen[9917]: Cookie : Good
Oct 28 22:07:43 nucosen nucosen[9917]: Response body ;
Oct 28 22:07:43 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 22:07:43 nucosen nucosen[9917]: 2023-10-28 22:07:43,198 [WARNING] W01 引用拒否発生, retrying in 640 seconds...
Oct 28 22:18:25 nucosen nucosen[9917]: 2023-10-28 22:18:25,778 [INFO] 400 Error Log ==========
Oct 28 22:18:25 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 22:18:25 nucosen nucosen[9917]: Cookie : Good
Oct 28 22:18:25 nucosen nucosen[9917]: Response body ;
Oct 28 22:18:25 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 22:18:25 nucosen nucosen[9917]: 2023-10-28 22:18:25,780 [WARNING] W01 引用拒否発生, retrying in 1280 seconds...
Oct 28 22:39:48 nucosen nucosen[9917]: 2023-10-28 22:39:48,396 [INFO] 400 Error Log ==========
Oct 28 22:39:48 nucosen nucosen[9917]: Target : https://lapi.spi.nicovideo.jp/v1/tools/live/contents/lv343217399/quotation
Oct 28 22:39:48 nucosen nucosen[9917]: Cookie : Good
Oct 28 22:39:48 nucosen nucosen[9917]: Response body ;
Oct 28 22:39:48 nucosen nucosen[9917]: {"meta":{"status":400,"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"}}
Oct 28 22:39:48 nucosen nucosen[9917]: 2023-10-28 22:39:48,399 [CRITICAL] 例外がキャッチされませんでした
Oct 28 22:39:48 nucosen nucosen[9917]: ```
Oct 28 22:39:48 nucosen nucosen[9917]: Traceback (most recent call last):
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/nucosen/nucosen.py", line 150, in run
Oct 28 22:39:48 nucosen nucosen[9917]:     quote.loop(currentLiveId, config(
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/nucosen/quote.py", line 189, in loop
Oct 28 22:39:48 nucosen nucosen[9917]:     once(liveId, videoId, session)
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
Oct 28 22:39:48 nucosen nucosen[9917]:     return caller(func, *(extras + args), **kw)
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/retry/api.py", line 73, in retry_decorator
Oct 28 22:39:48 nucosen nucosen[9917]:     return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/retry/api.py", line 33, in __retry_internal
Oct 28 22:39:48 nucosen nucosen[9917]:     return f()
Oct 28 22:39:48 nucosen nucosen[9917]:   File "/usr/local/lib/python3.10/dist-packages/nucosen/quote.py", line 181, in once
Oct 28 22:39:48 nucosen nucosen[9917]:     raise RetryRequired("W01 引用拒否発生")
Oct 28 22:39:48 nucosen nucosen[9917]: nucosen.quote.RetryRequired: W01 引用拒否発生
Oct 28 22:39:48 nucosen nucosen[9917]: ```

**Comment by komatti365** [comment]
自分では対応方法がわからないので、変数を削除して稼働し、同じエラーが発生したら可用性危機としてラベリングします

**Comment by sitting-cat** [comment]
`"errorCode":"INVALID_PARAMETER","errorMessage":"invalid id"`とあるので、指定している動画IDが誤っていませんか？

**Comment by komatti365** [comment]
30秒ほどの動画を指定してたので、エンディングにするにはおそらく短すぎたのかなと考えてます。

**Comment by komatti365** [comment]
追記です。環境変数を削除したにもかかわらず同様のエラーが発生しました。
暫定的な対応として、バージョンを安定版に巻き戻し運用しています。
現在のmasterバージョンで再検証を行ないます

**Comment by komatti365** [comment]
windows環境で起動したところ正常起動したため、おそらくバージョン管理の問題で不具合発生したようですね。
こちらは据え置きで

**Comment by sitting-cat** [comment]
安定版使用で解決した問題とのことでクローズします
