### ISSUE TITLE
エラー発生記録

### ISSUE THREAD

**Issue by sitting-cat** [nucosen/Broadcast#70]
WARNING @ nucosen.personality.randomSelection (__retry_internal)
503 Server Error: Service Temporarily Unavailable for url: https://api.search.nicovideo.jp/api/v2/snapshot/video/contents/search?q=%E6%9D%B1%E6%96%B9%E3%82%92%E6%AD%8C%E3%81%A3%E3%81%A6%E3%81%BF%E3%81%9F&targets=tagsExact&fields=contentId&filters%5BlengthSeconds%5D%5Bgte%5D=45&filters%5BlengthSeconds%5D%5Blte%5D=600&_sort=-lastCommentTime&_context=NUCOSen+backend&_limit=10&_offset=35, retrying in 16 seconds...
CRITICAL @ nucosen.nucosen (run)
例外がキャッチされませんでした
Traceback (most recent call last):
  File "/home/manager/.local/lib/python3.10/site-packages/nucosen/nucosen.py", line 126, in run
    selection = personality.randomSelection(
  File "/home/manager/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/manager/.local/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/manager/.local/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/manager/.local/lib/python3.10/site-packages/nucosen/personality.py", line 59, in randomSelection
    "q": tags.pop(),
IndexError: pop from empty list

**Comment by sitting-cat** [comment]
#63 と重複。
